### ISSUE TITLE
Add new testing tools to the list (Hacktoberfest accepted) :loudspeaker:  

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/awesome-testing-tools#51]
Add new testing tools that you have find useful to the existing lists :raised_hands:

**Comment by aayushbisen** [comment]
Hey @ZoranPandovski 👋 

Added an awesome framework Nightwatch.js in #52.

**Comment by Matrix278** [comment]
Hi, added one more tool in #53
